import { addIcons } from 'ionicons';
import {
  searchOutline,
  homeOutline,
  bagOutline,
  cartOutline,
  play,
  pause,
  heart,
  heartOutline,
  bookmark,
  bookmarkOutline,
  star,
  starHalf,
  starOutline,
  person,
  personOutline,
  personCircleOutline,
  settingsOutline,
  sunnyOutline,
  moonOutline,
  close,
  chevronBack,
  chevronForward,
  chevronDown,
  add,
  remove,
  playBack,
  playForward,
  volumeHighOutline,
  volumeMuteOutline,
  arrowForward,
  barcodeOutline,
  cameraOutline,
  trashOutline,
  checkmark,
  cubeOutline,
  listOutline,
  menuOutline,
  gridOutline,
  informationCircleOutline,
  flagOutline,
  filmOutline,
  eyeOutline,
  cloudUploadOutline,
  expand,
  textOutline,
  notificationsOutline,
  logOutOutline,
  createOutline,
  playCircle,
  pricetagOutline,
} from 'ionicons/icons';

export function registerAppIcons(): void {
  addIcons({
    'search-outline': searchOutline,
    'home-outline': homeOutline,
    'bag-outline': bagOutline,
    'cart-outline': cartOutline,
    play,
    pause,
    heart,
    'heart-outline': heartOutline,
    bookmark,
    'bookmark-outline': bookmarkOutline,
    star,
    'star-half': starHalf,
    'star-outline': starOutline,
    person,
    'person-outline': personOutline,
    'person-circle-outline': personCircleOutline,
    'settings-outline': settingsOutline,
    'sunny-outline': sunnyOutline,
    'moon-outline': moonOutline,
    close,
    'chevron-back': chevronBack,
    'chevron-forward': chevronForward,
    'chevron-down': chevronDown,
    add,
    remove,
    'play-back': playBack,
    'play-forward': playForward,
    'volume-high-outline': volumeHighOutline,
    'volume-mute-outline': volumeMuteOutline,
    'arrow-forward': arrowForward,
    'barcode-outline': barcodeOutline,
    'camera-outline': cameraOutline,
    'trash-outline': trashOutline,
    checkmark,
    'cube-outline': cubeOutline,
    'list-outline': listOutline,
    'menu-outline': menuOutline,
    'grid-outline': gridOutline,
    'information-circle-outline': informationCircleOutline,
    'flag-outline': flagOutline,
    'film-outline': filmOutline,
    'eye-outline': eyeOutline,
    'cloud-upload-outline': cloudUploadOutline,
    expand,
    'text-outline': textOutline,
    'notifications-outline': notificationsOutline,
    'log-out-outline': logOutOutline,
    'create-outline': createOutline,
    'play-circle': playCircle,
    'pricetag-outline': pricetagOutline,
  });
}
